/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WrappedRouteImport } from './routes/wrapped'
import { Route as SponsorRadarRouteImport } from './routes/sponsor-radar'
import { Route as SponsorRouteImport } from './routes/sponsor'
import { Route as RecapRouteImport } from './routes/recap'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayRouteImport } from './routes/play'
import { Route as JoinRouteImport } from './routes/join'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const WrappedRoute = WrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRadarRoute = SponsorRadarRouteImport.update({
  id: '/sponsor-radar',
  path: '/sponsor-radar',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapRoute = RecapRouteImport.update({
  id: '/recap',
  path: '/recap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/recap': typeof RecapRoute
  '/sponsor': typeof SponsorRoute
  '/sponsor-radar': typeof SponsorRadarRoute
  '/wrapped': typeof WrappedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/recap': typeof RecapRoute
  '/sponsor': typeof SponsorRoute
  '/sponsor-radar': typeof SponsorRadarRoute
  '/wrapped': typeof WrappedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/play': typeof PlayRoute
  '/profile': typeof ProfileRoute
  '/recap': typeof RecapRoute
  '/sponsor': typeof SponsorRoute
  '/sponsor-radar': typeof SponsorRadarRoute
  '/wrapped': typeof WrappedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/join'
    | '/play'
    | '/profile'
    | '/recap'
    | '/sponsor'
    | '/sponsor-radar'
    | '/wrapped'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/join'
    | '/play'
    | '/profile'
    | '/recap'
    | '/sponsor'
    | '/sponsor-radar'
    | '/wrapped'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/join'
    | '/play'
    | '/profile'
    | '/recap'
    | '/sponsor'
    | '/sponsor-radar'
    | '/wrapped'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  JoinRoute: typeof JoinRoute
  PlayRoute: typeof PlayRoute
  ProfileRoute: typeof ProfileRoute
  RecapRoute: typeof RecapRoute
  SponsorRoute: typeof SponsorRoute
  SponsorRadarRoute: typeof SponsorRadarRoute
  WrappedRoute: typeof WrappedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wrapped': {
      id: '/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof WrappedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor-radar': {
      id: '/sponsor-radar'
      path: '/sponsor-radar'
      fullPath: '/sponsor-radar'
      preLoaderRoute: typeof SponsorRadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recap': {
      id: '/recap'
      path: '/recap'
      fullPath: '/recap'
      preLoaderRoute: typeof RecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  JoinRoute: JoinRoute,
  PlayRoute: PlayRoute,
  ProfileRoute: ProfileRoute,
  RecapRoute: RecapRoute,
  SponsorRoute: SponsorRoute,
  SponsorRadarRoute: SponsorRadarRoute,
  WrappedRoute: WrappedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
